services:
  - type: web
    name: chatbot-backend
    runtime: node
    rootDir: backend/render-api
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: CHROMA_API_KEY
        sync: false
      - key: CHROMA_TENANT
        sync: false
      - key: CHROMA_DATABASE
        sync: false
      - key: PORT
        value: 10000
